# Copyright (c) 2020 PaddlePaddle Authors. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


runner:
  # train_data_dir: "train_data"
  # train_reader_path: "fake_reader" # importlib format
  # train_data_dir: "train_data_emb"
  # train_reader_path: "static_reader"
  train_data_dir: "../../../../../dr_paper/PaddleRec/datasets/dr_amazon_book/drbook_train_1w/"  #"../../../datasets/dr_amazon_book/drbook_train_10w/"  #train_10w
  #train_data_dir: "demo_book_train" # "train_data_amazon"
  train_reader_path: "paper_trainer_reader" #"paper_v1"
  train_batch_size: 200
  epochs: 10

  use_gpu: False
  use_auc: False
  print_interval: 1 
  distributed_training: False #True
  data_partition: True
  #model_init_path: "output_model/0" # init model
  model_save_path: "./load_model/1w_model_dr_v0" # "output_model_dr"  
  # test_data_dir: "test_data"
  test_data_dir: "../../../../../dr_paper/PaddleRec/datasets/dr_amazon_book/drbook_test_2k/" # "../../../datasets/dr_amazon_book/drbook_test_2w" 
  # infer_reader_path: "fake_infer_reader" # importlib format
  # train_data_dir: "test_data_amazon"
  infer_reader_path: "paper_infer_reader"
  infer_batch_size: 20
  infer_load_path: "../../../../../dr_paper/PaddleRec/models/treebased/deep_retrieval/load_model/1w_model_dr_v0" # "./load_model/1w_model_dr_v0"
  infer_start_epoch: 0
  infer_end_epoch: 10

# hyper parameters of user-defined network
hyper_parameters:
  # optimizer config
  optimizer:
    class: Adam
    learning_rate: 0.001
    strategy: async
  # user-defined <key, value> pairs
  width: 3 #2 3 4
  height: 25  #100 #20
  beam_search_num: 15 # 50  #3
  item_path_volume: 3
  use_multi_task_learning: True
  multi_task_layer_size: [128,128,128]
  pernalize_path_to_item_count: True
  pernalize_factor: 3e-7
  pernal_uploops: 3
  poly_power: 3
  # item_count: 10000
  recall_num: 100
  em_execution_interval: 2


  data_format: amazon_book_behavior 
  user_embedding_size: 128
  # data_format: user_embedding
  item_emb_size: 64
  cat_emb_size: 64
  cat_count: 988
  item_count: 128939    # 63001
  is_sparse: False
